####################
# CircleCI configuration reference:
#   https://circleci.com/docs/2.0/configuration-reference
####################

version: 2

#####################################################
# Jobs: see https://circleci.com/docs/2.0/jobs-steps/
#####################################################

jobs:
  test:
    docker: # run the steps with Docker
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            apt-get update && \
                apt-get install -y openjdk-8-jdk && \
                apt-get install -y ant && \
                apt-get clean;

            # Fix certificate issues
            apt-get update && \
                apt-get install ca-certificates-java && \
                apt-get clean && \
                update-ca-certificates -f;

            # Setup JAVA_HOME
            JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/
            export JAVA_HOME

            python -m virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python -m pytest tests
            flake8 usage_report/ tests/ --max-line-length 100

#########################################################
# Workflows: see https://circleci.com/docs/2.0/workflows/
#########################################################

workflows:
  version: 2
  commit:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
